# Generated by Django 5.1.dev20240306045047 on 2024-04-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_6',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/post/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_7',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/post/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_8',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/post/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_9',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/post/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='check_1',
            field=models.BooleanField(default=True),
        ),
    ]
