# Generated by Django 5.1.dev20240306045047 on 2024-04-12 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_post_image_6_post_image_7_post_image_8_post_image_9_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30000)),
                ('work_time', models.CharField(blank=True, default='', max_length=3000, null=True)),
                ('image0', models.ImageField(blank=True, null=True, upload_to='uploads/works/')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='uploads/works/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='uploads/works/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='uploads/works/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='uploads/works/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='uploads/works/')),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('tools', models.TextField(blank=True, default='', null=True)),
                ('web_link', models.URLField(blank=True, max_length=10000, null=True)),
                ('source_code', models.URLField(blank=True, max_length=10000, null=True)),
                ('upload_in', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.categorywork')),
            ],
            options={
                'ordering': ('-upload_in',),
            },
        ),
    ]
