# Generated by Django 5.1.dev20240306045047 on 2024-04-12 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_categorywork_works'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorywork',
            options={'verbose_name_plural': 'category_works'},
        ),
        migrations.AlterModelOptions(
            name='works',
            options={'ordering': ('-upload_in',), 'verbose_name_plural': 'Works'},
        ),
    ]
