# Generated by Django 5.1.dev20240306045047 on 2024-04-13 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0006_alter_contact_name_alter_contact_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='subject',
            new_name='mobile',
        ),
    ]
