# Generated by Django 5.1.dev20240306045047 on 2024-04-14 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0007_rename_subject_contact_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30000)),
                ('project_complete', models.CharField(blank=True, default='', max_length=30000, null=True)),
                ('project_running', models.CharField(blank=True, default='', max_length=3000, null=True)),
                ('client', models.CharField(blank=True, default='', max_length=3000, null=True)),
            ],
            options={
                'verbose_name_plural': 'CounterSection',
            },
        ),
    ]
