# Generated by Django 5.1.dev20240306045047 on 2024-04-14 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0008_countersection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countersection',
            name='client',
        ),
        migrations.AddField(
            model_name='countersection',
            name='clients',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='countersection',
            name='project_complete',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='countersection',
            name='project_running',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
    ]
