# Generated by Django 5.1.dev20240306045047 on 2024-04-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0009_remove_countersection_client_countersection_clients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countersection',
            name='clients',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='countersection',
            name='project_complete',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='countersection',
            name='project_running',
            field=models.IntegerField(),
        ),
    ]
