# Generated by Django 5.0.4 on 2024-05-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0010_alter_countersection_clients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='code_1',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='step_1',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
